"""Initial migration

Revision ID: f45a45e6e471
Revises: 2722b8ab2870
Create Date: 2025-03-31 18:44:15.605654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f45a45e6e471'
down_revision: Union[str, None] = '2722b8ab2870'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('friends')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friends',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('friend_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='friends_friend_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='friends_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='friends_pkey')
    )
    # ### end Alembic commands ###
